Seeds
mimilettd/little_shop_of_useless_items pull request #2
Opened 2017-10-18 19:13 UTC by liambarstad

LIST OF CHANGES:
- seeds.rb requires all files in db/seeds directory
- install fakergem, betterlorem, imagesuckr
- seeds for musical_instruments, goldfish, and electronics

THINGS I'M UNSURE ON:
- sometimes imagesuckr api call fails
- method get_url for imagesuckr makes query to google images api every time it retrieves one image, could be overwritten

RSPEC GREEN?
no tests written

*MENTION GROUP MEMBER TO REVIEW PR*
@mimilettd @jimszalew @vaidashi

2017-10-18 20:44 UTC, jimszalew submitted a review, later dismissed
Is there going to be a specific command that runs all of these seed files? Will rake db:seed catch them all? If not I think it would be worth putting all seeding functions into the same seed file so that db:seed will catch it.

2017-10-18 20:47 UTC, jimszalew commented
Nevermind, saw that seed file requires all the other seed files. I still think this is inefficient at best. Also, travis seems to want a test database for the code to pass the CI checks.

2017-10-19 02:19 UTC, jimszalew requested changes
All of these seed files will most likely not work. Master branch has an updated database and relationships, requiring an item to belong to a store. These will need to be updated.

2017-10-19 19:56 UTC, jimszalew submitted a review, later dismissed
Looks good, I like the iterative approach to creating items. I think this should work with our current setup.

2017-10-24 01:43 UTC, liambarstad commented
@mimilettd @jimszalew @vaidashi 
I don't know why these checks are passing all of a sudden, but it looks good to go

2017-10-24 05:38 UTC, jimszalew commented on lib/tasks/reset.rake
> +Dir['./db/seeds/*.rb'].each {|file| require file }
I'm really sorry, I know you explained this file in person to us but I don't remember what it does. Can you give me a quick description please?

2017-10-24 23:48 UTC, closed without merging